# This is a basic workflow to help you get started with Actions

name: Build Flutter

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths-ignore: 
      - ".github/workflows/**"
      - "**.md"
      - "**.yaml"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - ".github/workflows/**"
      - "**.md"
      - "**.yaml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_android:
    name: 'Build Android APK and AppBundle'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle
  build_ios:
    name: 'Build iOS ipa'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      
